### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by ajstrand** [spielrs/yew_styles#58]
Hi,
I noticed there was a typo in the README.
It's located in the first sentence. 

> provide a style framework for yew that doesn't require any Javascrit

the fix should be as simple as changing Javascrit to JavaScript.

According [Wikipedia](https://en.wikipedia.org/wiki/JavaScript), the "S" in script should also be capitalized. 

Would I be able to work on that change?

Thanks,
Alex

**Comment by dancespiele** [comment]
You right. I could change it but if you want to do I really appreciate it. For this not only you need to change the README file form the root of the project, you also need to change:
* `crates/yew_styles/README`: it is the README of Yew Styles library,
* `crates/yew_styles/src/lib.rs`: for the the main page of the Rust API docs
* `crates/src/page/home_page.rs`: for the documentation pages (it shows visual examples)

Thanks in advance Alex

**Comment by ajstrand** [comment]
Sure, thanks for letting me contribute!

**Comment by dancespiele** [comment]
The fix typo for the rust doc API will be in the release 0.7.2. Thanks for your contributions Alex!

**Comment by ajstrand** [comment]
You're welcome!
