### ISSUE TITLE
Add screenshots of components

### ISSUE THREAD

**Issue by hamza1311** [spielrs/yew_styles#63]
Currently, the only way to know the styles look is to grab this crate and try it out. It'd be great if there were some examples of how each component looked like how [Angular Material](https://material.angular.io/components/categories) does.

It would be great if there were demos like that too but that would require having a website built with these styles which is a lot of work, especially considering that this project in its early stages. So including screenshots in docs on docs.rs or in this repo would be a welcome improvement.

**Comment by dancespiele** [comment]
It is right that there is not a published website at the moment which it is planned in the future however you can see the visual examples running the documentation page, you can find how do it [here](https://github.com/spielrs/yew_styles#run-the-documentation-page)

**Comment by dancespiele** [comment]
@hamza1311 from today there is already a website where you can find all the visual examples, thanks for you suggestion. This is the link https://yewstyles.spielrs.tech . I close this issuce
